name = "brrrand"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "e814825e2f4a44b882df59ccb3b33410"
preview_id = "4b8bf79f05d14edfa115b5224e236d69"

# Environment variables
[vars]
ENVIRONMENT = "production"
VITE_DEMO_MODE = "false"
VITE_SHOW_DEMO_TOGGLE = "false"
VITE_APP_VERSION = "1.0.0"
VITE_ENABLE_ANALYTICS = "true"
# Set these in Cloudflare dashboard:
# VITE_GA_MEASUREMENT_ID = "your-actual-ga-id"
# VITE_GTM_CONTAINER_ID = "your-actual-gtm-id"

# Static assets configuration for Workers
[site]
bucket = "./dist"
